import React, { createContext, useContext, useState, useEffect } from 'react';
import API from '../api/axios';

// Full translation dictionary — 13 languages, all UI strings
const TRANSLATIONS = {
  en: {
    home: "Home",
    market: "Market",
    pest: "Pest Alerts",
    crops: "Crop Picks",
    voiceConsultant: "Voice Consultant",
    diseaseScan: "Disease Scan",
    logout: "Logout",
    goodMorning: "Good Morning",
    farmer: "Farmer",
    weatherToday: "Today's Weather",
    marketSnapshot: "Market Snapshot",
    quickAccess: "Quick Access",
    naturalFarmingTip: "Natural Farming Tip",
    tapToAsk: "Tap mic and ask about pests, prices, or farming advice",
    selectLanguage: "Select Language",
    tapToSpeak: "Tap & hold to speak",
    listening: "Listening...",
    thinking: "KisanAI is thinking...",
    getFullReport: "Get Full Advisory Report",
    uploadLeafPhoto: "Upload Leaf Photo",
    diagnosing: "Diagnosing...",
    organicRemedy: "Organic Remedy",
    mandiPrices: "Mandi Prices",
    priceRising: "Rising ↑",
    priceFalling: "Falling ↓",
    priceStable: "Stable →",
    govtSchemes: "Government Schemes",
    applyNow: "Apply Now",
    qualifySchemes: "Schemes you qualify for",
    name: "Name",
    mobile: "Mobile",
    state: "State",
    district: "District",
    soilType: "Soil Type",
    farmSize: "Farm Size (acres)",
    login: "Login",
    signUp: "Sign Up",
    email: "Email",
    password: "Password",
    acres: "Acres",
    temp: "Temp",
    soilPH: "Soil pH",
    noWeeklyAdvisory: "No Weekly Advisory Yet",
    customizedSchedulesDesc: "Get customized schedules for irrigation, pest alerts, and sustainable tip tracking.",
    generateWeeklyPlan: "Generate Weekly Plan",
    irrigationSchedule: "Irrigation Schedule",
    pestWarnings: "Potential Pest Warnings",
    harvestOutlook: "Harvest Outlook",
    estDate: "Est. Date",
    yieldProjection: "Yield Projection",
    regeneratePlan: "Regenerate Plan",
    analyzingMarketData: "Analyzing market data...",
    cropSegment: "Crop Segment",
    avgPrice: "Avg Price",
    mandiPriceMovement: "Mandi Price Movement",
    last30Days: "Last 30 Days (per quintal)",
    noPriceTrends: "No price trends recorded yet.",
    verifiedMandiBuyers: "Verified Mandi Buyers",
    noDirectBuyers: "No direct buyers found for",
    risingTrend: "rising trend",
    fallingTrend: "falling trend",
    stableTrend: "stable trend",
    scanningDatabases: "Scanning regional databases...",
    activeThreats: "Active Regional Threats",
    active: "Active",
    allClearPest: "All clear! No active pest threats reported in your cluster.",
    reportPestSighting: "Report Pest Sighting",
    pestDiseaseName: "Pest/Disease Name",
    severityLevel: "Severity Level",
    broadcastSighting: "Broadcast Sighting to Cluster",
    consultingKrishi: "Consulting Krishi AI model...",
    failedToGenerate: "Failed to generate recommendations. Please try again.",
    topAlternativePick: "Top Alternative Pick",
    estProfit: "Est. Profit",
    perAcrePerSeason: "per acre per season",
    duration: "Duration",
    fromSeedToHarvest: "from seed to harvest",
    days: "Days",
    yieldExpectation: "Yield Expectation",
    bestSowingSeason: "Best Sowing Season",
    specialCareTips: "Special Care & Tips",
    matchedBuyerGuaranteed: "Matched Buyer Guaranteed",
    adoptCropThisSeason: "Adopt Crop This Season",
    interestRegistered: "Interest Registered ✓",
    localAgronomistsDesc: "Local cooperative agronomists will be assigned to support your transition.",
  },
  hi: {
    home: "होम",
    market: "बाज़ार",
    pest: "कीट अलर्ट",
    crops: "फसल सुझाव",
    voiceConsultant: "वॉइस सलाहकार",
    diseaseScan: "रोग पहचान",
    logout: "लॉगआउट",
    goodMorning: "सुप्रभात",
    farmer: "किसान",
    weatherToday: "आज का मौसम",
    marketSnapshot: "बाज़ार की झलक",
    quickAccess: "त्वरित पहुँच",
    naturalFarmingTip: "प्राकृतिक खेती टिप",
    tapToAsk: "माइक दबाएं और कीट, कीमत या खेती की सलाह पूछें",
    selectLanguage: "भाषा चुनें",
    tapToSpeak: "बोलने के लिए दबाएं",
    listening: "सुन रहा हूँ...",
    thinking: "KisanAI सोच रहा है...",
    getFullReport: "पूरी सलाह रिपोर्ट पाएं",
    uploadLeafPhoto: "पत्ती की फोटो अपलोड करें",
    diagnosing: "जांच हो रही है...",
    organicRemedy: "जैविक उपाय",
    mandiPrices: "मंडी भाव",
    priceRising: "बढ़ रहा ↑",
    priceFalling: "गिर रहा ↓",
    priceStable: "स्थिर →",
    govtSchemes: "सरकारी योजनाएं",
    applyNow: "अभी आवेदन करें",
    qualifySchemes: "आपके लिए योजनाएं",
    name: "नाम",
    mobile: "मोबाइल",
    state: "राज्य",
    district: "जिला",
    soilType: "मिट्टी का प्रकार",
    farmSize: "खेत का आकार (एकड़)",
    login: "लॉगिन",
    signUp: "साइन अप",
    email: "ईमेल",
    password: "पासवर्ड",
    acres: "एकड़",
    temp: "तापमान",
    soilPH: "मिट्टी pH",
    noWeeklyAdvisory: "अभी तक कोई साप्ताहिक सलाह नहीं",
    customizedSchedulesDesc: "सिंचाई, कीट अलर्ट और टिकाऊ खेती के सुझावों के लिए व्यक्तिगत कार्यक्रम प्राप्त करें।",
    generateWeeklyPlan: "साप्ताहिक योजना बनाएं",
    irrigationSchedule: "सिंचाई कार्यक्रम",
    pestWarnings: "संभावित कीट चेतावनी",
    harvestOutlook: "कटाई की संभावना",
    estDate: "अनुमानित तारीख",
    yieldProjection: "उपज का अनुमान",
    regeneratePlan: "योजना फिर से बनाएं",
    analyzingMarketData: "बाज़ार के आंकड़ों का विश्लेषण कर रहे हैं...",
    cropSegment: "फसल श्रेणी",
    avgPrice: "औसत मूल्य",
    mandiPriceMovement: "मंडी भाव में उतार-चढ़ाव",
    last30Days: "पिछले 30 दिन (प्रति क्विंटल)",
    noPriceTrends: "अभी तक कोई मूल्य रुझान दर्ज नहीं किया गया है।",
    verifiedMandiBuyers: "सत्यापित मंडी खरीदार",
    noDirectBuyers: "के लिए कोई सीधे खरीदार नहीं मिले।",
    risingTrend: "बढ़ता हुआ",
    fallingTrend: "घटता हुआ",
    stableTrend: "स्थिर",
    scanningDatabases: "क्षेत्रीय डेटाबेस को स्कैन कर रहे हैं...",
    activeThreats: "सक्रिय क्षेत्रीय खतरे",
    active: "सक्रिय",
    allClearPest: "सब ठीक है! आपके क्षेत्र में कोई सक्रिय कीट खतरा नहीं है।",
    reportPestSighting: "कीट की शिकायत दर्ज करें",
    pestDiseaseName: "कीट/बीमारी का नाम",
    severityLevel: "गंभीरता का स्तर",
    broadcastSighting: "पूरे क्षेत्र को सचेत करें",
    consultingKrishi: "कृषि एआई मॉडल से सलाह ले रहे हैं...",
    failedToGenerate: "सुझाव उत्पन्न करने में विफल। कृपया पुन: प्रयास करें।",
    topAlternativePick: "शीर्ष वैकल्पिक फसल",
    estProfit: "अनुमानित लाभ",
    perAcrePerSeason: "प्रति एकड़ प्रति सीजन",
    duration: "अवधि",
    fromSeedToHarvest: "बीज से कटाई तक",
    days: "दिन",
    yieldExpectation: "अनुमानित उपज",
    bestSowingSeason: "बुवाई का सबसे अच्छा समय",
    specialCareTips: "विशेष देखभाल और सुझाव",
    matchedBuyerGuaranteed: "खरीदार की गारंटी",
    adoptCropThisSeason: "इस सीजन में इस फसल को अपनाएं",
    interestRegistered: "रुचि दर्ज की गई ✓",
    localAgronomistsDesc: "आपकी सहायता के लिए स्थानीय सहकारी कृषि वैज्ञानिकों को नियुक्त किया जाएगा।",
  },
  ta: {
    home: "முகப்பு",
    market: "சந்தை",
    pest: "பூச்சி எச்சரிக்கை",
    crops: "பயிர் பரிந்துரை",
    voiceConsultant: "குரல் ஆலோசகர்",
    diseaseScan: "நோய் கண்டறிதல்",
    logout: "வெளியேறு",
    goodMorning: "காலை வணக்கம்",
    farmer: "விவசாயி",
    weatherToday: "இன்றைய வானிலை",
    marketSnapshot: "சந்தை நிலவரம்",
    quickAccess: "விரைவு அணுகல்",
    naturalFarmingTip: "இயற்கை விவசாய குறிப்பு",
    tapToAsk: "மைக் அழுத்தி பூச்சி, விலை அல்லது விவசாய ஆலோசனை கேளுங்கள்",
    selectLanguage: "மொழி தேர்வு",
    tapToSpeak: "பேச தட்டவும்",
    listening: "கேட்கிறேன்...",
    thinking: "KisanAI யோசிக்கிறது...",
    getFullReport: "முழு ஆலோசனை அறிக்கை பெறுங்கள்",
    uploadLeafPhoto: "இலை புகைப்படம் பதிவேற்றவும்",
    diagnosing: "கண்டறிகிறது...",
    organicRemedy: "இயற்கை தீர்வு",
    mandiPrices: "மண்டி விலைகள்",
    priceRising: "உயர்கிறது ↑",
    priceFalling: "குறைகிறது ↓",
    priceStable: "நிலையானது →",
    govtSchemes: "அரசு திட்டங்கள்",
    applyNow: "இப்போது விண்ணப்பம் செய்க",
    qualifySchemes: "உங்களுக்கான திட்டங்கள்",
    name: "பெயர்",
    mobile: "மொபைல்",
    state: "மாநிலம்",
    district: "மாவட்டம்",
    soilType: "மண் வகை",
    farmSize: "நில அளவு (ஏக்கர்)",
    login: "உள்நுழைய",
    signUp: "பதிவு செய்க",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    acres: "ஏக்கர்",
    temp: "வெப்பநிலை",
    soilPH: "மண் pH",
    noWeeklyAdvisory: "வாராந்திர ஆலோசனை இன்னும் இல்லை",
    customizedSchedulesDesc: "நீர் பாசனம், பூச்சி எச்சரிக்கைகள் மற்றும் விவசாய குறிப்புகளுக்கான தனிப்பயனாக்கப்பட்ட அட்டவணையைப் பெறுங்கள்.",
    generateWeeklyPlan: "வாராந்திர திட்டத்தை உருவாக்கு",
    irrigationSchedule: "நீர்ப்பாசன அட்டவணை",
    pestWarnings: "சாத்தியமான பூச்சி எச்சரிக்கைகள்",
    harvestOutlook: "அறுவடை பார்வை",
    estDate: "மதிப்பிடப்பட்ட தேதி",
    yieldProjection: "மகசூல் கணிப்பு",
    regeneratePlan: "திட்டத்தை மீண்டும் உருவாக்கு",
    analyzingMarketData: "சந்தை தரவுகளை பகுப்பாய்வு செய்கிறது...",
    cropSegment: "பயிர் பிரிவு",
    avgPrice: "சராசரி விலை",
    mandiPriceMovement: "மண்டி விலை மாற்றம்",
    last30Days: "கடந்த 30 நாட்கள் (ஒரு குவிண்டாலுக்கு)",
    noPriceTrends: "விலை போக்குகள் இன்னும் பதிவு செய்யப்படவில்லை.",
    verifiedMandiBuyers: "சரிபார்க்கப்பட்ட மண்டி வாங்குபவர்கள்",
    noDirectBuyers: "இதற்கான நேரடி வாங்குபவர்கள் யாரும் இல்லை",
    risingTrend: "உயரும் போக்கு",
    fallingTrend: "குறையும் போக்கு",
    stableTrend: "நிலையான போக்கு",
    scanningDatabases: "பிராந்திய தரவுத்தளங்களை ஸ்கேன் செய்கிறது...",
    activeThreats: "செயலில் உள்ள பிராந்திய அச்சுறுத்தல்கள்",
    active: "செயலில் உள்ளவை",
    allClearPest: "எல்லாம் நலம்! உங்கள் பகுதியில் செயலில் உள்ள பூச்சி அச்சுறுத்தல்கள் எதுவும் இல்லை.",
    reportPestSighting: "பூச்சி பாதிப்பை பதிவு செய்",
    pestDiseaseName: "பூச்சி/நோய் பெயர்",
    severityLevel: "பாதிப்பு அளவு",
    broadcastSighting: "பாதிப்பை மற்ற விவசாயிகளுக்கு எச்சரி",
    consultingKrishi: "கிருஷி ஏஐ மாடலிடம் ஆলোசிக்கிறது...",
    failedToGenerate: "பரிந்துரைகளை உருவாக்குவதில் தோல்வி. மீண்டும் முயற்சிக்கவும்.",
    topAlternativePick: "சிறந்த மாற்று பயிர்",
    estProfit: "மதிப்பிடப்பட்ட லாபம்",
    perAcrePerSeason: "ஒரு ஏக்கருக்கு ஒரு பருவத்திற்கு",
    duration: "கால அளவு",
    fromSeedToHarvest: "விதையிலிருந்து அறுவடை வரை",
    days: "நாட்கள்",
    yieldExpectation: "மகசூல் எதிர்பார்ப்பு",
    bestSowingSeason: "சிறந்த விதைப்பு பருவம்",
    specialCareTips: "சிறப்பு கவனிப்பு & குறிப்புகள்",
    matchedBuyerGuaranteed: "வாங்குபவர் உத்தரவாதம்",
    adoptCropThisSeason: "இந்த பருவத்தில் இந்த பயிரை பயிரிடுங்கள்",
    interestRegistered: "விருப்பம் பதிவு செய்யப்பட்டது ✓",
    localAgronomistsDesc: "உங்களது மாற்றத்திற்கு உதவ உள்ளூர் கூட்டுறவு வேளாண் நிபுணர்கள் நியமிக்கப்படுவார்கள்.",
  },
  te: {
    home: "హోమ్",
    market: "మార్కెట్",
    pest: "పురుగు హెచ్చరికలు",
    crops: "పంట సూచనలు",
    voiceConsultant: "వాయిస్ సలహాదారు",
    logout: "లాగ్అవుట్",
    goodMorning: "శుభోదయం",
    farmer: "రైతు",
    weatherToday: "నేటి వాతావరణం",
    marketSnapshot: "మార్కెట్ స్నాప్షాట్",
    quickAccess: "త్వరిత యాక్సెస్",
    naturalFarmingTip: "സഹజ వ్యవసాయ చిట్కా",
    tapToAsk: "మైక్ నొక్కి పురుగులు, ధరలు లేదా వ్యవసాయ సలహా అడగండి",
    selectLanguage: "భాష ఎంచుకోండి",
    tapToSpeak: "మాట్లాడటానికి నొక్కండి",
    listening: "వింటున్నాను...",
    thinking: "KisanAI ఆలోచిస్తోంది...",
    getFullReport: "పూర్తి సలహా నివేదిక పొందండి",
    uploadLeafPhoto: "ఆకు ఫోటో అప్లోడ్ చేయండి",
    diagnosing: "నిర్ధారిస్తోంది...",
    organicRemedy: "సేంద్రియ పరిష్కారం",
    mandiPrices: "మండి ధరలు",
    priceRising: "పెరుగుతోంది ↑",
    priceFalling: "తగ్గుతోంది ↓",
    priceStable: "స్థిరంగా →",
    govtSchemes: "ప్రభుత్వ పథకాలు",
    applyNow: "ఇప్పుడే దరఖాస్తు చేయండి",
    qualifySchemes: "మీకు వర్తించే పథకాలు",
    name: "పేరు",
    mobile: "మొబైல்",
    state: "రాష్ట్రం",
    district: "జిల్లా",
    soilType: "నేల రకం",
    farmSize: "పొలం పరిమాణం (ఎకరాలు)",
    login: "లాగిన్",
    signUp: "సైన్ అప్",
    email: "ఇమెయిల్",
    password: "పాస్వర్డ్",
    acres: "ఎకరాలు",
    temp: "ఉష్ణోగ్రత",
    soilPH: "నేల pH",
  },
  kn: {
    home: "ಮುಖಪುಟ",
    market: "ಮಾರುಕಟ್ಟೆ",
    pest: "ಕೀಟ ಎಚ್ಚರಿಕೆ",
    crops: "ಬೆಳೆ ಸಲಹೆ",
    voiceConsultant: "ಧ್ವನಿ ಸಲಹೆಗಾರ",
    logout: "ಲಾಗ್ಔಟ್",
    goodMorning: "ಶುಭೋದಯ",
    farmer: "ರೈತ",
    weatherToday: "ಇಂದಿನ ಹವಾಮಾನ",
    marketSnapshot: "ಮಾರುಕಟ್ಟೆ ಮಾಹಿತಿ",
    quickAccess: "ತ್ವರಿತ ಪ್ರವೇಶ",
    naturalFarmingTip: "ನೈಸರ್ಗಿಕ ಕೃಷಿ ಸಲಹೆ",
    tapToAsk: "ಮೈಕ್ ಒತ್ತಿ ಕೀಟಗಳು, ದರಗಳು ಅಥವಾ ಕೃಷಿ ಸಲಹೆ ಕೇಳಿ",
    selectLanguage: "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
    tapToSpeak: "ಮಾತನಾಡಲು ಒತ್ತಿ ಹಿಡಿಯಿರಿ",
    listening: "ಕೇಳುತ್ತಿದ್ದೇನೆ...",
    thinking: "KisanAI ಯೋಚಿಸುತ್ತಿದೆ...",
    getFullReport: "ಪೂರ್ಣ ಸಲಹಾ ವರದಿ ಪಡೆಯಿರಿ",
    uploadLeafPhoto: "ಎಲೆ ಫೋಟೋ ಅಪ್ಲೋಡ್ ಮಾಡಿ",
    diagnosing: "ಪತ್ತೆ ಹಚ್ಚಲಾಗುತ್ತಿದೆ...",
    organicRemedy: "ಸಾವಯವ ಪರಿಹಾರ",
    mandiPrices: "ಮಾರುಕಟ್ಟೆ ದರಗಳು",
    priceRising: "ಏರುತ್ತಿದೆ ↑",
    priceFalling: "ಕುಸಿಯುತ್ತಿದೆ ↓",
    priceStable: "ಸ್ಥಿರವಾಗಿದೆ →",
    govtSchemes: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    applyNow: "ಈಗಲೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    qualifySchemes: "ನಿಮಗೆ ಅನ್ವయಿಸುವ ಯೋಜನೆಗಳು",
    name: "ಹೆಸರು",
    mobile: "ಮೊಬೈಲ್",
    state: "ರಾಜ್ಯ",
    district: "ಜಿಲ್ಲೆ",
    soilType: "ಮಣ್ಣಿನ ವಿಧ",
    farmSize: "ಗಾತ್ರ (ಎಕರೆ)",
    login: "ಲಾಗಿನ್",
    signUp: "ಸೈನ್ ಅಪ್",
    email: "ಇಮೇಲ್",
    password: "ಪಾಸ್ವರ್ಡ್",
    acres: "ಎಕರೆಗಳು",
    temp: "ತಾಪಮಾನ",
    soilPH: "ಮಣ್ಣಿನ pH",
  },
  ml: {
    home: "ഹോം",
    market: "മാർക്കറ്റ്",
    pest: "കീട മുന്നറിയിപ്പ്",
    crops: "വിള തിരഞ്ഞെടുപ്പ്",
    voiceConsultant: "വോയ്‌സ് കൺസൾട്ടന്റ്",
    logout: "ലോഗ്ഔട്ട്",
    goodMorning: "സുപ്രഭാതം",
    farmer: "കർഷകൻ",
    weatherToday: "ഇന്നത്തെ കാലാവസ്ഥ",
    marketSnapshot: "മാർക്കറ്റ് വിവരങ്ങൾ",
    quickAccess: "ദ്രുത പ്രവേശനം",
    naturalFarmingTip: "പ്രകൃതി കൃഷി ടിപ്പ്",
    tapToAsk: "മൈക്ക് അമർത്തി കീടങ്ങളെക്കുറിച്ചോ വിലയെക്കുറിച്ചോ ചോദിക്കുക",
    selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    tapToSpeak: "സംസാരിക്കാൻ അമർത്തി പിടിക്കുക",
    listening: "കേൾക്കുന്നു...",
    thinking: "KisanAI ചിന്തിക്കുന്നു...",
    getFullReport: "പൂർണ്ണ റിപ്പോർട്ട് നേടുക",
    uploadLeafPhoto: "ഇലയുടെ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക",
    diagnosing: "രോഗനിർണയം നടത്തുന്നു...",
    organicRemedy: "ജൈവ പ്രതിവിധി",
    mandiPrices: "മാർക്കറ്റ് വിലകൾ",
    priceRising: "കൂടുന്നു ↑",
    priceFalling: "കുറയുന്നു ↓",
    priceStable: "മാറ്റമില്ലാതെ →",
    govtSchemes: "സർക്കാർ പദ്ധതികൾ",
    applyNow: "അപേക്ഷിക്കുക",
    qualifySchemes: "നിങ്ങൾക്ക് യോഗ്യതയുള്ള പദ്ധതികൾ",
    name: "പേര്",
    mobile: "മൊബൈൽ",
    state: "സംസ്ഥാനം",
    district: "ജില്ല",
    soilType: "മണ്ണ് തരം",
    farmSize: "സ്ഥലം (ഏക്കർ)",
    login: "ലോഗിൻ",
    signUp: "സൈൻ അപ്പ്",
    email: "ഇമെയിൽ",
    password: "പാസ്‌വേഡ്",
    acres: "ഏക്കർ",
    temp: "താപനില",
    soilPH: "മണ്ണ് pH",
  },
  mr: {
    home: "होम",
    market: "बाजार",
    pest: "कीड अलर्ट",
    crops: "पीक निवड",
    voiceConsultant: "व्हॉइस सल्लागार",
    logout: "लॉगआउट",
    goodMorning: "शुभप्रभात",
    farmer: "शेतकरी",
    weatherToday: "आजचे हवामान",
    marketSnapshot: "बाजार माहिती",
    quickAccess: "जलद प्रवेश",
    naturalFarmingTip: "सेंद्रिय शेती सल्ला",
    tapToAsk: "माईक दाबून कीड, किंमत किंवा शेतीचा सल्ला विचारा",
    selectLanguage: "भाषा निवडा",
    tapToSpeak: "बोलण्यासाठी दाबून ठेवा",
    listening: "ऐकत आहे...",
    thinking: "KisanAI विचार करत आहे...",
    getFullReport: "पूर्ण सल्ला अहवाल मिळवा",
    uploadLeafPhoto: "पानाचा फोटो अपलोड करा",
    diagnosing: "तपासणी सुरू आहे...",
    organicRemedy: "सेंद्रिय उपाय",
    mandiPrices: "बाजार भाव",
    priceRising: "वाढत आहे ↑",
    priceFalling: "घसरत आहे ↓",
    priceStable: "स्थिर आहे →",
    govtSchemes: "शासकीय योजना",
    applyNow: "आता अर्ज करा",
    qualifySchemes: "पात्र योजना",
    name: "नाव",
    mobile: "मोबाईल",
    state: "राज्य",
    district: "जिल्हा",
    soilType: "मातीचा प्रकार",
    farmSize: "शेत आकार (एकर)",
    login: "लॉगिन",
    signUp: "साइन अप",
    email: "ईमेल",
    password: "पासवर्ड",
    acres: "एकर",
    temp: "तापमान",
    soilPH: "माती pH",
  },
  gu: {
    home: "હોમ",
    market: "બજાર",
    pest: "કીટક ચેતવણી",
    crops: "પાક પસંદગી",
    voiceConsultant: "વોઈસ કન્સલ્ટન્ટ",
    logout: "લોગઆઉટ",
    goodMorning: "સુપ્રભાત",
    farmer: "ખેડૂત",
    weatherToday: "આજનું હવામાન",
    marketSnapshot: "બજાર સ્નેપશોટ",
    quickAccess: "ઝડપી પ્રવેશ",
    naturalFarmingTip: "કુદરતી ખેતી ટિપ",
    tapToAsk: "માઇક દબાવીને કીટક, ભાવ કે ખેતીની સલાહ પૂછો",
    selectLanguage: "ભાષા પસંદ કરો",
    tapToSpeak: "બોલવા માટે દબાવી રાખો",
    listening: "સાંભળી રહ્યું છે...",
    thinking: "KisanAI વિચારી રહ્યું છે...",
    getFullReport: "સંપૂર્ણ અહેવાલ મેળવો",
    uploadLeafPhoto: "પાંદડાનો ફોટો અપલોડ કરો",
    diagnosing: "નિદાન થઈ રહ્યું છે...",
    organicRemedy: "ઓર્ગેनिक ઉપાય",
    mandiPrices: "મંડી ભાવ",
    priceRising: "વધી રહ્યું છે ↑",
    priceFalling: "ઘટી રહ્યું છે ↓",
    priceStable: "સ્થિર છે →",
    govtSchemes: "સરકારી યોજનાઓ",
    applyNow: "અત્યારે જ અરજી કરો",
    qualifySchemes: "યોગ્ય યોજનાઓ",
    name: "નામ",
    mobile: "મોબાઈલ",
    state: "રાજ્ય",
    district: "જિલ્લો",
    soilType: "જમીનનો પ્રકાર",
    farmSize: "જમીનનું માપ (એકર)",
    login: "લોગઇન",
    signUp: "સાઇન અપ",
    email: "ઇમેઇલ",
    password: "પાસવર્ડ",
    acres: "એકર",
    temp: "તાપમાન",
    soilPH: "જમીન pH",
  },
  pa: {
    home: "ਹੋਮ",
    market: "ਮਾਰਕੀਟ",
    pest: "ਕੀੜੇ ਅਲਰਟ",
    crops: "ਫ਼ਸਲ ਚੋਣ",
    voiceConsultant: "ਵਾਇਸ ਸਲਾਹਕਾਰ",
    logout: "ਲੌਗਆਊਟ",
    goodMorning: "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ",
    farmer: "ਕਿਸਾਨ",
    weatherToday: "ਅੱਜ ਦਾ ਮੌਸਮ",
    marketSnapshot: "ਮਾਰਕੀਟ ਦੀ ਝਲਕ",
    quickAccess: "ਤੁਰੰਤ ਪਹੁੰਚ",
    naturalFarmingTip: "ਕੁਦਰਤੀ ਖੇਤੀ ਟਿਪ",
    tapToAsk: "ਮਾਈਕ ਦਬਾ ਕੇ ਕੀੜੇ, ਕੀਮਤ ਜਾਂ ਖੇਤੀ ਸਲਾਹ ਪੁੱਛੋ",
    selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
    tapToSpeak: "ਬੋਲਣ ਲਈ ਦਬਾ ਕੇ ਰੱਖੋ",
    listening: "ਸੁਣ ਰਿਹਾ ਹੈ...",
    thinking: "KisanAI ਸੋਚ ਰਿਹਾ ਹੈ...",
    getFullReport: "ਪੂਰੀ ਸਲਾਹ ਰਿਪੋਰਟ ਪ੍ਰਾਪਤ ਕਰੋ",
    uploadLeafPhoto: "ਪੱਤੇ ਦੀ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ",
    diagnosing: "ਜਾਂਚ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...",
    organicRemedy: "ਜੈਵਿਕ ਉਪਾਅ",
    mandiPrices: "ਮੰਡੀ ਦੇ ਭਾਅ",
    priceRising: "ਵਧ ਰਿਹਾ ਹੈ ↑",
    priceFalling: "ਘਟ ਰਿਹਾ ਹੈ ↓",
    priceStable: "ਸਥਿਰ ਹੈ →",
    govtSchemes: "ਸਰਕਾਰੀ ਸਕੀਮਾਂ",
    applyNow: "ਹੁਣੇ ਅਪਲਾਈ ਕਰੋ",
    qualifySchemes: "ਤੁਹਾਡੇ ਲਈ ਯੋਗ ਸਕੀਮਾਂ",
    name: "ਨਾਮ",
    mobile: "ਮੋਬਾਈਲ",
    state: "ਸੂਬਾ",
    district: "ਜ਼ਿਲ੍ਹਾ",
    soilType: "ਮਿੱਟੀ ਦੀ ਕਿਸਮ",
    farmSize: "ਫ਼ਾਰਮ ਸਾਈਜ਼ (ਏਕੜ)",
    login: "ਲੌਗਇਨ",
    signUp: "ਸਾਈਨ ਅੱਪ",
    email: "ਈਮੇਲ",
    password: "ਪਾਸਵਰਡ",
    acres: "ਏਕੜ",
    temp: "ਤਾਪਮਾਨ",
    soilPH: "ਮਿੱਟੀ pH",
  },
  bn: {
    home: "হোম",
    market: "বাজার",
    pest: "পোকামাকড় সতর্কবার্তা",
    crops: "ফসল নির্বাচন",
    voiceConsultant: "ভয়েস পরামর্শদাতা",
    logout: "লগআউট",
    goodMorning: "সুপ্রভাত",
    farmer: "কৃষক",
    weatherToday: "আজকের আবহাওয়া",
    marketSnapshot: "বাজারের তথ্য",
    quickAccess: "সহজ অ্যাক্সেস",
    naturalFarmingTip: "প্রাকৃতিক চাষের টিপস",
    tapToAsk: "মাইক টিপে পোকা, দাম বা চাষের পরামর্শ জিজ্ঞাসা করুন",
    selectLanguage: "ভাষা নির্বাচন করুন",
    tapToSpeak: "কথা বলতে টিপে রাখুন",
    listening: "শুনছি...",
    thinking: "KisanAI ভাবছে...",
    getFullReport: "সম্পূর্ণ রিপোর্ট পান",
    uploadLeafPhoto: "পাতার ছবি আপলোড করুন",
    diagnosing: "রোগ নির্ণয় হচ্ছে...",
    organicRemedy: "জৈবিক প্রতিকার",
    mandiPrices: "মন্ডির দর",
    priceRising: "বাড়ছে ↑",
    priceFalling: "কমছে ↓",
    priceStable: "স্থিতিশীল →",
    govtSchemes: "সরকারি প্রকল্প",
    applyNow: "আবেদন করুন",
    qualifySchemes: "আপনার জন্য প্রকল্পগুলি",
    name: "নাম",
    mobile: "মোবাইল",
    state: "রাজ্য",
    district: "জেলা",
    soilType: "মাটির ধরণ",
    farmSize: "জমির পরিমাণ (একর)",
    login: "লগইন",
    signUp: "সাইন আপ",
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    acres: "একর",
    temp: "তাপমাত্রা",
    soilPH: "মাটির pH",
  },
  or: {
    home: "ହୋମ",
    market: "ବଜାର",
    pest: "ପୋକ ସତର୍କତା",
    crops: "ଫସଲ ଚୟନ",
    voiceConsultant: "ସ୍ୱର ପରାమର୍ଶଦାତା",
    logout: "ଲଗଆଉଟ",
    goodMorning: "ଶୁଭ ସକାଳ",
    farmer: "କୃଷକ",
    weatherToday: "ଆଜିର ପାଣିପਾଗ",
    marketSnapshot: "ବଜାର ସୂଚନା",
    quickAccess: "ଶୀଘ୍ର ପ୍ରବେଶ",
    naturalFarmingTip: "ପ୍ରାକୃତିକ ଚାଷ ଟିପ୍ସ",
    tapToAsk: "ମାଇକ୍ ଦବାଇ କୀଟନାଶକ, ଦର କିମ୍ବା ଚਾଷ ବିଷୟରେ ପଚାରନ୍ତু",
    selectLanguage: "ଭାଷା ବାଛନ୍ତୁ",
    tapToSpeak: "କହିବା ପାଇଁ ଦବାଇ ରଖନ୍ତୁ",
    listening: "ଶୁଣୁଛି...",
    thinking: "KisanAI ଚିନ୍ତା କରុଛି...",
    getFullReport: "ସମ୍ପୂର୍ଣ୍ଣ ରିପୋର୍ଟ ପାଆନ୍ତୁ",
    uploadLeafPhoto: "ପତ୍ରର ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତு",
    diagnosing: "රୋଗ ନିରୂପଣ ଚାଲିଛି...",
    organicRemedy: "ଜୈବିକ ପ୍ରତିକାର",
    mandiPrices: "ମଣ୍ଡି ଦର",
    priceRising: "ବଢୁଛି ↑",
    priceFalling: "କମୁଛି ↓",
    priceStable: "ସ୍ଥିর ଅଛି →",
    govtSchemes: "ସରକାରୀ ଯୋଜନା",
    applyNow: "ଆବେਦନ କରନ୍ତୁ",
    qualifySchemes: "ଆପଣଙ୍କ ପାଇଁ ଯୋଜନା",
    name: "ନାମ",
    mobile: "ମୋବାଇଲ୍",
    state: "ରାଜ୍ୟ",
    district: "ଜିଲ୍ଲା",
    soilType: "ମାଟିର ପ୍ରକାର",
    farmSize: "ଜମିର ଆକਾਰ (ଏକର)",
    login: "ଲଗଇନ୍",
    signUp: "ਸਾਈਨ ਅਪ",
    email: "ଇମେଲ୍",
    password: "ପାସୱାର୍ଡ",
    acres: "ଏକର",
    temp: "ତାପମାତ୍ରା",
    soilPH: "ମାଟି pH",
  },
  as: {
    home: "হোম",
    market: "বজাৰ",
    pest: "কীট সতৰ্কতা",
    crops: "শস্য নিৰ্বাচন",
    voiceConsultant: "ভয়েচ পৰামৰ্শদাতা",
    logout: "লগআউট",
    goodMorning: "সুপ্রভাত",
    farmer: "কৃষক",
    weatherToday: "আজিৰ বতৰ",
    marketSnapshot: "বজাৰ খতিয়ান",
    quickAccess: "ক্ষিপ্ৰ প্ৰৱেশ",
    naturalFarmingTip: "প্ৰাকৃতিক খেতিৰ পৰামৰ্শ",
    tapToAsk: "মাইক টিপি কীট, দৰ বা খেতিৰ পৰামৰ্শ সোধক",
    selectLanguage: "ভাষা বাছনি কৰক",
    tapToSpeak: "কবলৈ টিপি ৰাখক",
    listening: "শুনি আছো...",
    thinking: "KisanAI ভাবি আছে...",
    getFullReport: "পূৰ্ণ পৰামৰ্শ লাভ কৰক",
    uploadLeafPhoto: "পাতৰ ফটো আপলোড কৰক",
    diagnosing: "নিদান চলি আছে...",
    organicRemedy: "জৈৱিক উপায়",
    mandiPrices: "মন্ডি দৰ",
    priceRising: "বৃদ্ধি হৈছে ↑",
    priceFalling: "হ্ৰাস পাইছে ↓",
    priceStable: "স্থিৰ আছে →",
    govtSchemes: "চৰকাৰী আঁচনি",
    applyNow: "আবেদন কৰক",
    qualifySchemes: "উপযুক্ত আঁচনিসমূহ",
    name: "নাম",
    mobile: "মোবাইল",
    state: "ৰাজ্য",
    district: "জিলা",
    soilType: "মাটিৰ প্ৰকাৰ",
    farmSize: "মাটিৰ পৰিমাণ (একৰ)",
    login: "লগইন",
    signUp: "ছাইন আপ",
    email: "ইমেইল",
    password: "পাছৱৰ্ড",
    acres: "একৰ",
    temp: "উত্তাপ",
    soilPH: "মাটিৰ pH",
  },
  ur: {
    home: "ہوم",
    market: "منڈی",
    pest: "کیڑے مکوڑے الرٹ",
    crops: "فصل کا انتخاب",
    voiceConsultant: "وائس کنسلٹنٹ",
    logout: "لاگ آؤٹ",
    goodMorning: "صبح بخیر",
    farmer: "کسان",
    weatherToday: "آج کا موسم",
    marketSnapshot: "منڈی کی جھلک",
    quickAccess: "فوری رسائی",
    naturalFarmingTip: "قدرتی کاشتکاری کا مشورہ",
    tapToAsk: "مائیک دبا کر کیڑے مکوڑے، قیمت یا کاشتکاری کا مشورہ پوچھیں",
    selectLanguage: "زبان منتخب کریں",
    tapToSpeak: "بولنے کے لیے دبا کر رکھیں",
    listening: "سن رہا ہے...",
    thinking: "KisanAI سوچ رہا ہے...",
    getFullReport: "مکمل رپورٹ حاصل کریں",
    uploadLeafPhoto: "پتے کی تصویر اپ لوڈ کریں",
    diagnosing: "تشخیص ہو رہی ہے...",
    organicRemedy: "نامیاتی علاج",
    mandiPrices: "منڈی کے نرخ",
    priceRising: "بڑھ رہا ہے ↑",
    priceFalling: "گر رہا ہے ↓",
    priceStable: "مستحکم ہے →",
    govtSchemes: "سرکاری اسکیمیں",
    applyNow: "ابھی اپلائی کریں",
    qualifySchemes: "اہل اسکیمیں",
    name: "نام",
    mobile: "موبائل",
    state: "ریاست",
    district: "ضلع",
    soilType: "مٹی کی قسم",
    farmSize: "فارم کا رقبہ (ایکڑ)",
    login: "لاگ ان",
    signUp: "سائن اپ",
    email: "ای میل",
    password: "پاس ورڈ",
    acres: "ایکڑ",
    temp: "درجہ حرارت",
    soilPH: "مٹی کا pH",
  }
};

// Quick-suggest voice bubbles per language
export const VOICE_SUGGESTIONS = {
  en: ["Tomato price today?", "Early blight remedy?", "PM-KISAN eligibility?", "ZBNF cropping method?"],
  hi: ["टमाटर का दाम?", "अगेती झुलसा का उपाय?", "पीएम-किसान पात्रता?", "जैविक खेती विधि?"],
  ta: ["தக்காளி விலை?", "ஆர்லி ப்லைட் தீர்வு?", "பிஎம்-கிசான் தகுதி?", "இயற்கை விவசாயம்?"],
  te: ["టమాటా ధర?", "తొందర ముడత నివారణ?", "పిఎం-కిసాన్ అర్హత?", "సహజ వ్యవసాయం?"],
  kn: ["ಟೊಮೇಟೊ ಬೆಲೆ?", "ಆರ್ಲಿ ಬ್ಲೈಟ್ ಪರಿಹಾರ?", "ಪಿಎಂ-ಕಿಸಾನ್?", "ನೈಸರ್ಗಿಕ ಕೃಷಿ?"],
  ml: ["തക്കാളി വില?", "ഏർലി ബ്ലൈറ്റ് പരിഹാരം?", "PM-KISAN?", "പ്രകൃതി കൃഷി?"],
  mr: ["टोमॅटो भाव?", "अर्ली ब्लाइट उपाय?", "पीएम-किसान?", "नैसर्गिक शेती?"],
  gu: ["ટામેટા ભાવ?", "અર્લી બ્લાઈટ ઉપાય?", "PM-KISAN?", "કુદરતી ખેતી?"],
  pa: ["ਟਮਾਟਰ ਭਾਅ?", "ਅਰਲੀ ਬਲਾਈਟ ਉਪਾਅ?", "PM-KISAN?", "ਕੁਦਰਤੀ ਖੇਤੀ?"],
  bn: ["টমেটো দাম?", "আর্লি ব্লাইট সমাধান?", "PM-KISAN?", "প্রাকৃতিক চাষ?"],
  or: ["ଟମାଟୋ ଦର?", "ଅର୍ଲି ବ୍ଲਾਈਟ?", "PM-KISAN?", "ପ୍ରାକୃତିକ ଚାଷ?"],
  as: ["টমেটো দাম?", "আর্লি ব্লাইট?", "PM-KISAN?", "প্ৰাকৃতিক খেতি?"],
  ur: ["ٹماٹر کی قیمت?", "ارلی بلائٹ علاج?", "PM-KISAN?", "قدرتی کاشتکاری?"],
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem("kisanai_lang") || "en"
  );

  const changeLanguage = async (code) => {
    setLanguage(code);
    localStorage.setItem("kisanai_lang", code);
    const token = localStorage.getItem('smartagri_token');
    if (token) {
      try {
        const res = await API.put('/api/auth/profile', { language: code });
        localStorage.setItem('smartagri_user', JSON.stringify(res.data));
      } catch (err) {
        console.error("Failed to sync preferred language to backend:", err);
      }
    }
  };

  const t = (key) => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be inside LanguageProvider");
  return ctx;
};
